-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module FamilyTree.Object.Family exposing (..)

import FamilyTree.InputObject
import FamilyTree.Interface
import FamilyTree.Object
import FamilyTree.Scalar
import FamilyTree.ScalarCodecs
import FamilyTree.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


people : SelectionSet decodesTo FamilyTree.Object.Person -> SelectionSet (List decodesTo) FamilyTree.Object.Family
people object_ =
    Object.selectionForCompositeField "people" [] object_ (identity >> Decode.list)


relationships : SelectionSet decodesTo FamilyTree.Object.Relationship -> SelectionSet (List decodesTo) FamilyTree.Object.Family
relationships object_ =
    Object.selectionForCompositeField "relationships" [] object_ (identity >> Decode.list)
