-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module FamilyTree.Object.FullDate exposing (..)

import FamilyTree.InputObject
import FamilyTree.Interface
import FamilyTree.Object
import FamilyTree.Scalar
import FamilyTree.ScalarCodecs
import FamilyTree.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


day : SelectionSet (Maybe Int) FamilyTree.Object.FullDate
day =
    Object.selectionForField "(Maybe Int)" "day" [] (Decode.int |> Decode.nullable)


month : SelectionSet (Maybe Int) FamilyTree.Object.FullDate
month =
    Object.selectionForField "(Maybe Int)" "month" [] (Decode.int |> Decode.nullable)


year : SelectionSet (Maybe Int) FamilyTree.Object.FullDate
year =
    Object.selectionForField "(Maybe Int)" "year" [] (Decode.int |> Decode.nullable)
