-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module FamilyTree.Object.Person exposing (..)

import FamilyTree.InputObject
import FamilyTree.Interface
import FamilyTree.Object
import FamilyTree.Scalar
import FamilyTree.ScalarCodecs
import FamilyTree.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


birthDate : SelectionSet decodesTo FamilyTree.Object.FullDate -> SelectionSet decodesTo FamilyTree.Object.Person
birthDate object_ =
    Object.selectionForCompositeField "birthDate" [] object_ identity


deathDate : SelectionSet decodesTo FamilyTree.Object.FullDate -> SelectionSet decodesTo FamilyTree.Object.Person
deathDate object_ =
    Object.selectionForCompositeField "deathDate" [] object_ identity


firstName : SelectionSet String FamilyTree.Object.Person
firstName =
    Object.selectionForField "String" "firstName" [] Decode.string


id : SelectionSet FamilyTree.ScalarCodecs.Id FamilyTree.Object.Person
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (FamilyTree.ScalarCodecs.codecs |> FamilyTree.Scalar.unwrapCodecs |> .codecId |> .decoder)


lastName : SelectionSet String FamilyTree.Object.Person
lastName =
    Object.selectionForField "String" "lastName" [] Decode.string


relationshipId : SelectionSet (Maybe FamilyTree.ScalarCodecs.Id) FamilyTree.Object.Person
relationshipId =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "relationshipId" [] (FamilyTree.ScalarCodecs.codecs |> FamilyTree.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


sex : SelectionSet String FamilyTree.Object.Person
sex =
    Object.selectionForField "String" "sex" [] Decode.string
