-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module FamilyTree.Object.Relationship exposing (..)

import FamilyTree.InputObject
import FamilyTree.Interface
import FamilyTree.Object
import FamilyTree.Scalar
import FamilyTree.ScalarCodecs
import FamilyTree.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


children : SelectionSet (List FamilyTree.ScalarCodecs.Id) FamilyTree.Object.Relationship
children =
    Object.selectionForField "(List ScalarCodecs.Id)" "children" [] (FamilyTree.ScalarCodecs.codecs |> FamilyTree.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.list)


id : SelectionSet FamilyTree.ScalarCodecs.Id FamilyTree.Object.Relationship
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (FamilyTree.ScalarCodecs.codecs |> FamilyTree.Scalar.unwrapCodecs |> .codecId |> .decoder)
