-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module FamilyTree.InputObject exposing (..)

import FamilyTree.Interface
import FamilyTree.Object
import FamilyTree.Scalar
import FamilyTree.ScalarCodecs
import FamilyTree.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


buildChildParams : ChildParamsRequiredFields -> ChildParams
buildChildParams required =
    { birthDate = required.birthDate, deathDate = required.deathDate, firstName = required.firstName, sex = required.sex }


type alias ChildParamsRequiredFields =
    { birthDate : FullDateParams
    , deathDate : FullDateParams
    , firstName : String
    , sex : String
    }


{-| Type for the ChildParams input object.
-}
type alias ChildParams =
    { birthDate : FullDateParams
    , deathDate : FullDateParams
    , firstName : String
    , sex : String
    }


{-| Encode a ChildParams into a value that can be used as an argument.
-}
encodeChildParams : ChildParams -> Value
encodeChildParams input =
    Encode.maybeObject
        [ ( "birthDate", encodeFullDateParams input.birthDate |> Just ), ( "deathDate", encodeFullDateParams input.deathDate |> Just ), ( "firstName", Encode.string input.firstName |> Just ), ( "sex", Encode.string input.sex |> Just ) ]


buildFullDateParams : (FullDateParamsOptionalFields -> FullDateParamsOptionalFields) -> FullDateParams
buildFullDateParams fillOptionals =
    let
        optionals =
            fillOptionals
                { day = Absent, month = Absent, year = Absent }
    in
    { day = optionals.day, month = optionals.month, year = optionals.year }


type alias FullDateParamsOptionalFields =
    { day : OptionalArgument Int
    , month : OptionalArgument Int
    , year : OptionalArgument Int
    }


{-| Type for the FullDateParams input object.
-}
type alias FullDateParams =
    { day : OptionalArgument Int
    , month : OptionalArgument Int
    , year : OptionalArgument Int
    }


{-| Encode a FullDateParams into a value that can be used as an argument.
-}
encodeFullDateParams : FullDateParams -> Value
encodeFullDateParams input =
    Encode.maybeObject
        [ ( "day", Encode.int |> Encode.optional input.day ), ( "month", Encode.int |> Encode.optional input.month ), ( "year", Encode.int |> Encode.optional input.year ) ]


buildSpouseParams : SpouseParamsRequiredFields -> SpouseParams
buildSpouseParams required =
    { birthDate = required.birthDate, deathDate = required.deathDate, firstName = required.firstName, lastName = required.lastName, sex = required.sex }


type alias SpouseParamsRequiredFields =
    { birthDate : FullDateParams
    , deathDate : FullDateParams
    , firstName : String
    , lastName : String
    , sex : String
    }


{-| Type for the SpouseParams input object.
-}
type alias SpouseParams =
    { birthDate : FullDateParams
    , deathDate : FullDateParams
    , firstName : String
    , lastName : String
    , sex : String
    }


{-| Encode a SpouseParams into a value that can be used as an argument.
-}
encodeSpouseParams : SpouseParams -> Value
encodeSpouseParams input =
    Encode.maybeObject
        [ ( "birthDate", encodeFullDateParams input.birthDate |> Just ), ( "deathDate", encodeFullDateParams input.deathDate |> Just ), ( "firstName", Encode.string input.firstName |> Just ), ( "lastName", Encode.string input.lastName |> Just ), ( "sex", Encode.string input.sex |> Just ) ]
