-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module FamilyTree.ScalarCodecs exposing (..)

import FamilyTree.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    FamilyTree.Scalar.Id


codecs : FamilyTree.Scalar.Codecs Id
codecs =
    FamilyTree.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
